### DISCUSSION TITLE
What information should the basis field contain?

### DISCUSSION THREAD

**Discussion by ross-spencer** [richardlehane/siegfried#196] [Ideas]
Given this example from a TGA: `'extension match tga; byte match at 4261283, 18'` is Siegfried saying it read 4mb to read the last 18 bytes of the file, or is it seeking 18 bytes from the end of the file? TGA uses is identified using: `TRUEVISION-XFILE.<null> last 18 bytes of the file`. So, only 18 bytes are needed. 

Does it matter? I imagined the max offsets creating small window either side of the file payload, e.g. 1000 bytes max from BOF or 500 bytes max from EOF. Establishing through SF alone requires knowing which values may be BOF or EOF?

```yaml
filename : 'MARBLES.TGA'
filesize : 4261301
modified : 2022-06-02T13:14:16+02:00
errors   :
matches  :
  - ns      : 'pronom'
    id      : 'fmt/402'
    format  : 'Truevision TGA Bitmap'
    version : '2.0'
    mime    :
    basis   : 'extension match tga; byte match at 4261283, 18'
    warning :
```
