### ISSUE TITLE
PHP files recognized as HTML

### ISSUE THREAD

**Issue by despens** [richardlehane/siegfried#40]
Siegfried says:
```yaml
---
filename : 'files/index.php'
filesize : 884
errors   : 
matches  :
  - id      : pronom
    puid    : fmt/471
    format  : 'Hypertext Markup Language'
    version : '5'
    mime    : 'text/html'
    basis   : 'byte match at 0, 15'
    warning : 'extension mismatch'
```
However, the second to last line in the file contains a simple PHP instruction in the form of
```php
<?php echo rand(1, 1000); ?>
```
I agree there's not much PHP in there, but this should be recognized anyway. Is this a PRONOM or a Siegfried problem?
