### ISSUE TITLE
gzip detected in WARCs when server sends gzip-encoded responses?

### ISSUE THREAD

**Issue by despens** [richardlehane/siegfried#57]
When analysing WARC files, Siegfried often returns the GZIP Format for HTML responses:

```yaml
---
filename : 'despens-mbcbftworig-20150912122950303-00000-8-0431e4b3640d.warc.gz/20150912123008/http:/www.teleportacia.org/war/warb.htm'
filesize : 100
modified : 2015-09-12T12:30:08Z
errors   : 
sha1     : e5f8bcea337f2e66904e88db6a22ff7b1943700e
matches  :
  - id      : pronom
    puid    : x-fmt/266
    format  : 'GZIP Format'
    version : 
    mime    : 'application/x-gzip'
    basis   : 'byte match at 0, 3'
    warning : 'extension mismatch; MIME mismatch'
```

Indeed this file is served with gzip compression by the server and was recorded that way:

```sh
$ curl -I -H 'Accept-Encoding: gzip,deflate' http://www.teleportacia.org/war/warb.htm
HTTP/1.1 200 OK
Date: Sun, 08 Nov 2015 07:30:43 GMT
Server: Apache/2.2.22 (Ubuntu)
Last-Modified: Tue, 20 Jan 2015 06:04:19 GMT
ETag: "81061-83-50d0f35a17ec0"
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 100
Content-Type: text/html
```

But the information that the server response was gzipped is, I think, not accurate, since it is not the actual *data format*, it is just the *encoding*. The `Content-Type` correctly points out this is `text/html`. I guess Siegfried would need to un-gzip any response that is encoded via gzip and do an analysis on that. Otherwise any `text/*` response, which could be JSON, HTML, XML, etc, could be showing up as GZIP.

**Comment by richardlehane** [comment]
Hey Dragan
when sf is running in -z mode it *should* just keep recursively descending whenever it encounters an archive format... so I would have expected that if a gzip (or zip or tar) was detected within a warc, it would already try to unpack and give you the results for the unpacked stream (although the MIME wouldn't get passed along & this might be something to tweak). Is the result immediately following the one in your report for the ungzipped stream??

**Comment by despens** [comment]
Indeed, you are right, the "unpacked" data is following the gzipped ones, like this:

```yaml
---
filename : 'despens-mbcbftworig-20150912122950303-00000-8-0431e4b3640d.warc.gz/20150912123009/http:/www.teleportacia.org/war/103.htm'
filesize : 174
modified : 2015-09-12T12:30:09Z
errors   : 
sha1     : 282242ead3258b719610e575cedb74118cda538c
matches  :
  - id      : pronom
    puid    : x-fmt/266
    format  : 'GZIP Format'
    version : 
    mime    : 'application/x-gzip'
    basis   : 'byte match at 0, 3'
    warning : 'extension mismatch; MIME mismatch'
---
filename : 'despens-mbcbftworig-20150912122950303-00000-8-0431e4b3640d.warc.gz/20150912123009/http:/www.teleportacia.org/war/103.htm/103'
filesize : 237
modified : 1970-01-01T01:00:00+01:00
errors   : 
sha1     : 9c5f3015c081ff5feb94aee0fdd50f77fe3a1628
matches  :
  - id      : pronom
    puid    : fmt/96
    format  : 'Hypertext Markup Language'
    version : 
    mime    : 'text/html'
    basis   : 'byte match at [[[10 5]] [[230 7]]] (signature 1/2)'
    warning : 'extension mismatch'
```

However, the URL `http:/www.teleportacia.org/war/103.htm/103` doesn't exist in the WARC and seems like a stand-in for the de-compressed data. This means that the "extension mismatch" is in fact not happening and the data, should I want to extract it from the WARC, would not be accessible via the `filename` property, I'd have to guess the actual URL.

I think  that if the `Content-Encoding` header is set, maybe Siegfried has to note that into another property field and ignore it otherwise?

Here is the relevant excerpt from the WARC:

```
WARC/1.0
WARC-Type: response
WARC-Record-ID: <urn:uuid:278abefe-7ed6-46ef-a135-97744e94fc82>
WARC-Date: 2015-09-12T12:30:09Z
WARC-Target-URI: http://www.teleportacia.org/war/103.htm
WARC-IP-Address: 185.21.100.12
Content-Type: application/http;msgtype=response
Content-Length: 455
WARC-Block-Digest: sha1:efcb633605b42fe39c50265ecb393efc92999048
WARC-Payload-Digest: sha1:282242ead3258b719610e575cedb74118cda538c

HTTP/1.1 200 OK
Date: Sat, 12 Sep 2015 12:52:30 GMT
Server: Apache/2.2.22 (Ubuntu)
Last-Modified: Tue, 20 Jan 2015 06:04:19 GMT
ETag: "81063-ed-50d0f35a17ec0"
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 174
Content-Type: text/html
```

The `Content-Type` is clearly present, but that gets lost, along with the original URL, when descending into the gzipped blob.
